### ISSUE TITLE
How to reproduce the result on the demo page

### ISSUE THREAD

**Issue by yoyoNTNU** [scnuhealthy/VTON360#13]
Hello, when I run this project using your demo data and the original codebase, I don't get the same results as on the demo page. What's going on? Or do I need to modify some code?

Also, I noticed that the MV attention weights in [here](https://github.com/scnuhealthy/VTON360/blob/main/src/multiview_consist_edit/pipelines/pipeline_tryon_multi.py#L143) are set to all 1 matrix.
Does this need to be commented?

<img width="1221" height="751" alt="Image" src="https://github.com/user-attachments/assets/1c7151f5-7fb4-4ebb-99ae-2d58c75941cd" />

left: my result(origin code)  
mid: demo page result 
right: my result (comment [it](https://github.com/scnuhealthy/VTON360/blob/main/src/multiview_consist_edit/pipelines/pipeline_tryon_multi.py#L143))
These are 3D reconstruction results

**Comment by scnuhealthy** [comment]
Thanks. This is a mistake when uploading the code. Set all 1 matrix is for the ablation study.  Now this is fixed.

**Comment by yoyoNTNU** [comment]
Hi, @scnuhealthy ,
Even if I use the correct weight matrix, I still can't get the same GS reconstruction results as shown on the demo page. Could you also share the VTON360 inference results (before to 3D)?

**Comment by scnuhealthy** [comment]
It seems that your 3D reconstruction results are similar to mine. These images are the results after multiple view editing and post-processing. 
![Image](https://github.com/user-attachments/assets/e26a3374-e91d-4986-be34-ee38e46aead6#width=50%)
![Image](https://github.com/user-attachments/assets/e975c401-1f02-447d-a48f-e35d52d41ca5#width=50%)
![Image](https://github.com/user-attachments/assets/a7822c72-58f8-4e59-acf5-bed7b2c51327#width=50%)
![Image](https://github.com/user-attachments/assets/8fee414a-aa7b-42de-8336-39298422a66c#width=50%)

**Comment by yoyoNTNU** [comment]
Oh, I see. I haven't run post-production yet, so the facial area might be changed. I'll try that. Thanks so much!
